<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
			<div class="panel-heading"  style="font-size: 16px; font-weight:bold;">
				Config
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								Your OPDS catalog URL
							</div>
							<div class="panel-body">
								<div class="input-group <?php echo (!$token['enabled'] ? 'has-error' : '') ?>">
  									<input type="text" class="form-control" value="<?php echo $this->url('catalog', array('hash' => $token['hash']), array('force_canonical' => true)) ?>" readonly <?php echo (!$token['enabled'] ? 'style="text-decoration: line-through;"' : '') ?> >
  									<span class="input-group-btn">
	       								<a href="<?php echo $this->url('application/default', array('controller' => 'config', 'action' => 'refreshToken')) ?>" class="btn <?php echo (!$token['enabled'] ? 'btn-danger' : 'btn-default') ?>" type="button">
        									<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
       									</a>
    								</span>
    							</div>								
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								Manage subscriptions
							</div>
							<div class="panel-body">
								<form>
									<label>Check the subscritions you want to receive</label>
									<div class="checkbox">
										<label>
											<input type="checkbox"> Weekly update about new books
										</label>
  									</div>
									<button type="submit" class="btn btn-default pull-right">Submit</button>  									
								</form>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								Change password
							</div>
							<div class="panel-body">
								<form>
									<div class="form-group">
    									<input type="password" class="form-control" id="changePasswordOld" name="changePasswordOld" placeholder="Old Password">
  									</div>
									<div class="form-group">
    									<input type="password" class="form-control" id="changePasswordNew1" name="changePasswordNew1" placeholder="New Password">
  									</div>
									<div class="form-group">
    									<input type="password" class="form-control" id="changePasswordNew2" name="changePasswordNew2" placeholder="Retype new Password">
  									</div>
									<button type="submit" class="btn btn-default pull-right">Submit</button>  									
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>