<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-default">
			<div class="panel-heading"  style="font-size: 16px; font-weight:bold;">
				Config
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								Your OPDS catalog URL
							</div>
							<div class="panel-body">
								<div class="input-group <?php echo (!$token['enabled'] ? 'has-error' : '') ?>">
  									<input type="text" class="form-control" value="<?php echo $this->url('catalog', array('hash' => $token['hash']), array('force_canonical' => true)) ?>" readonly <?php echo (!$token['enabled'] ? 'style="text-decoration: line-through;"' : '') ?> >
  									<span class="input-group-btn">
	       								<a href="<?php echo $this->url('application/default', array('controller' => 'config', 'action' => 'refreshToken')) ?>" class="btn <?php echo (!$token['enabled'] ? 'btn-danger' : 'btn-default') ?>" type="button">
        									<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
       									</a>
    								</span>
    							</div>								
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								Manage subscriptions
							</div>
							<div class="panel-body">
								<form>
									<label>Check the subscritions you want to receive</label>
									<div class="checkbox">
										<label>
											<input id="weeklyNews" name="weeklyNews" type="checkbox" <?php echo ($user->weeklynews == 1 ? 'checked' : '');?>> Weekly update about new books
										</label>
  									</div>
									<button type="submit" class="btn btn-default pull-right">Submit</button>  									
								</form>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								Change password
							</div>
							<div class="panel-body">
								<form id="changePasswordForm" action="<?php echo $this->url('application/default', array('controller' => 'user', 'action' => 'changePassword')) ?>" method="post" enctype="multipart/form-data">
									<div class="form-group" id="passwordGroup">
    									<input type="password" class="form-control" id="newPassword" name="newPassword" placeholder="New Password">
  									</div>
									<div class="form-group" id="password2Group">
    									<input type="password" class="form-control" id="newPassword2" name="newPassword2" placeholder="Retype new Password">
  									</div>
									<button class="btn btn-default pull-right" type="button" onclick="validate()">Submit</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
    function validate()
    {
        result = true;
        errorMsg = 'Validation error';

        if ($("#newPassword").val() == $("#newPassword2").val()){
        	$("#password2Group").removeClass('has-error');
        } else {
        	errorMsg = "Passowrd don't match!";
        	$('#password2Group').addClass('has-error');
        	result = false;
        }

        if ($("#newPassword").val()){
        	$("#passwordGroup").removeClass('has-error');
        } else {
        	errorMsg = "You need to write a password!";
        	$('#passwordGroup').addClass('has-error');
        	result = false;
        }
 
        if (!result) {
             alert(errorMsg);
        } else {
        	$('#changePasswordForm').submit();
        }
    }
</script>