<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('BookCloud')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/public/css/style.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/public/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/public/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/public/js/jquery.min.js') ?>

    </head>
    <body style="background: url(<?php echo $this->basePath() . '/public/images/back_books.jpg' ?>) no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
    <div class="container">
        <div class="hero-unit" style="background-color: rgba(0,0,0,0.7)">
        	<div class="row" style="text-align: center">
        		<div class="span4 offset1" style="padding: 20px">
                    <img src="<?php echo $this->basePath() . '/public/images/logoHD.png' ?>" style="max-width: 100%">
        		</div>
        		<div class="span4" style="padding: 20px 40px 0px 20px">
                    <div class="input-group">
                        <form action="<?php echo $this->url('application/default', array('controller'=>'user', 'action'=>'login'));?>" method="post" enctype="multipart/form-data" name="form_login" id="form_login">
                            <input name="email" type="text" class="form-control" style="width:100%; font-size: 18px; height:36px" placeholder="email" value="<?php echo (($this->user) ? $this->user->email : '');?>"><br><br>
                            <input name="password" type="password" class="form-control" style="width:100%; font-size: 18px; height:36px" placeholder="password"><br><br>
                            <input type="submit" class="btn btn-primary" style="font-size: 18px; padding:10px 30px 10px 30px" value="Sign in">
                        </form>
                    </div>
        		</div>
        	</div>
        </div>
    </div>
    </body>
</html>